#include <stdio.h>

int chart_1[17][2];
int chart_2[17][2];
int chart_3[17][2];
int chart_4[17][2];
int chart_5[17][2];
void COVID19_chart_gyeonggi(void);
void COVID19_chart_seoul(void);
void COVID19_chart_busan(void);
void COVID19_chart_gyeongnam(void);
void COVID19_chart_incheon(void);
void COVID19_chart_gyeongbuk(void);
void COVID19_chart_daegu(void);
void COVID19_chart_chungnam(void);
void COVID19_chart_jeonnam(void);
void COVID19_chart_jeonbuk(void);
void COVID19_chart_chungbuk(void);
void COVID19_chart_gangwon(void);
void COVID19_chart_daejeon(void);
void COVID19_chart_gwangju(void);
void COVID19_chart_ulsan(void);
void COVID19_chart_jeju(void);
void COVID19_chart_sejong(void);